version: '3'
services:
  web:
    container_name: icade_web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
     - DEBIAN_FRONTEND=noninteractive
     - TZ=Europe/Paris
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_NAME=icade
     - DB_USER=admin
     - DB_PASS=adminPass
    depends_on:
      - postgres
    ports:
      - 8080:80
    volumes:
      - ./Back:/var/www/Back:cached
      - ./Back/vendor:/var/www/Back/vendor:delegated

  react:
    container_name: icade_react
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    ports:
      - "3001:3000"
      - "35729:35729"
    volumes:
      - ./Front:/var/www/Front/

  postgres:
    container_name: icade_postgres
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: icade
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminPass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: icade_adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  dbdata: